apiVersion: v2
name: teable
description: A Helm chart for Teable - A modern collaborative database platform
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/teableio/teable
sources:
  - https://github.com/teableio/teable
maintainers:
  - name: Teable Team
    email: contact@teable.io
keywords:
  - database
  - collaboration
  - productivity
  - low-code

# Dependencies
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    # condition: postgres.enabled
  - name: redis
    version: "19.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    # condition: redis.enabled
  - name: minio
    version: "14.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    # condition: minio.enabled
