apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teable.fullname" . }}-secret
  labels:
    {{- include "teable.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database sensitive information
  PRISMA_DATABASE_URL: {{ include "teable.databaseUrl" . | quote }}

  # Application secrets
  BACKEND_JWT_SECRET: {{ .Values.teable.jwtSecret | quote }}
  BACKEND_SESSION_SECRET: {{ .Values.teable.sessionSecret | quote }}

  # MinIO authentication
  BACKEND_STORAGE_PUBLIC_BUCKET: {{ .Values.storage.publicBucket | quote }}
  BACKEND_STORAGE_PRIVATE_BUCKET: {{ .Values.storage.privateBucket | quote }}
  BACKEND_STORAGE_MINIO_ACCESS_KEY: {{ include "teable.minioAccessKey" . | quote }}
  BACKEND_STORAGE_MINIO_SECRET_KEY: {{ include "teable.minioSecretKey" . | quote }}

  # Redis authentication
  BACKEND_CACHE_REDIS_URI: {{ include "teable.redisUri" . | quote }}
