apiVersion: v1
kind: ConfigMap
metadata:
  name: teable-config
  namespace: teable
  labels:
    app.kubernetes.io/name: teable
    app.kubernetes.io/instance: teable
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: manual
data:
  # Application base configuration, public access domain
  PUBLIC_ORIGIN: "http://teable.local"

  # Storage configuration
  BACKEND_STORAGE_PROVIDER: "minio"
  # Public endpoint, important! Must be accessible by end users
  BACKEND_STORAGE_MINIO_ENDPOINT: "minio.default.svc.cluster.local:9000"
  # Same as above but with protocol
  STORAGE_PREFIX: "http://minio.default.svc.cluster.local:9000"
  # Internal endpoint
  BACKEND_STORAGE_MINIO_INTERNAL_ENDPOINT: "host.docker.internal"
  # Public port, typically 443 or 9000
  BACKEND_STORAGE_MINIO_PORT: "9000"
  # Internal port, typically 80 or 9000
  BACKEND_STORAGE_MINIO_INTERNAL_PORT: "9000"
  # Enable HTTPS, note: if Teable uses HTTPS, MinIO must also use HTTPS to avoid CORS issues
  BACKEND_STORAGE_MINIO_USE_SSL: "false"

  # Cache configuration, fixed value
  BACKEND_CACHE_PROVIDER: "redis"

  # Other configurations, fixed values
  NEXT_ENV_IMAGES_ALL_REMOTE: "true"
  PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: "1"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
